variables:
  ArmTemplateRoot: '$(Build.SourcesDirectory)\Resources\ArmTemplates'     
  SolutionBaseName: 'Dfc.App.JobCategories'
  BuildPlatform: 'any cpu'
  BuildConfiguration: 'release'

resources:
  repositories:
  - repository: self
  - repository: dfc-devops
    type: github
    name: SkillsFundingAgency/dfc-devops
    ref: refs/tags/v1.8.5
    endpoint: 'GitHub (ESFA)'

pool:
  name: NCS - CI and CD
  demands:
  - msbuild
  - visualstudio

stages:
- stage: Build
  displayName: Build, Test and Analyze
  jobs:
  #Build and test resources
  - job: ARMtemplates
    steps:
    - template: AzureDevOpsTemplates/Build/dfc-arm-build.yml@dfc-devops
      parameters:
        ArmTemplateRoot: $(ArmTemplateRoot)

  #Build and test web application
  - job: BuildTestAndAnalyzeWeb
    steps:
    - template: AzureDevOpsTemplates\Build\StepTemplates\dfc-dotnetcore-build-sonar.yml@dfc-devops
      parameters:
        SolutionBaseName: $(SolutionBaseName)
        BuildPlatform: 'any cpu'
        BuildConfiguration: 'release'
        TestSuffix: 'UnitTests'
        DotNetCoreVersion: '3.1.101'

  #Build and test function application
  - job: BuildTestAndAnalyzeFunction
    steps:
    - template: AzureDevOpsTemplates\Build\StepTemplates\dfc-dotnetcore-build-sonar.yml@dfc-devops
      parameters:
        SolutionBaseName: $(SolutionBaseName).MessageFunctionApp
        BuildPlatform: 'any cpu'
        BuildConfiguration: 'release'
        DotNetCoreVersion: '3.1.101'
